// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NatSys.DAL;

#nullable disable

namespace NatSys.DAL.Migrations
{
    [DbContext(typeof(NatSysDbContext))]
    [Migration("20260827220306_InicialNatSys")]
    partial class InicialNatSys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AtletaPrueba", b =>
                {
                    b.Property<int>("AtletaIdPersona")
                        .HasColumnType("int");

                    b.Property<int>("PruebasIdPrueba")
                        .HasColumnType("int");

                    b.HasKey("AtletaIdPersona", "PruebasIdPrueba");

                    b.HasIndex("PruebasIdPrueba");

                    b.ToTable("AtletaPrueba");
                });

            modelBuilder.Entity("GrupoPermiso", b =>
                {
                    b.Property<int>("GruposIdGrupo")
                        .HasColumnType("int");

                    b.Property<int>("PermisosIdPermiso")
                        .HasColumnType("int");

                    b.HasKey("GruposIdGrupo", "PermisosIdPermiso");

                    b.HasIndex("PermisosIdPermiso");

                    b.ToTable("GrupoPermiso");
                });

            modelBuilder.Entity("GrupoUsuario", b =>
                {
                    b.Property<int>("GruposIdGrupo")
                        .HasColumnType("int");

                    b.Property<int>("UsuariosIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("GruposIdGrupo", "UsuariosIdUsuario");

                    b.HasIndex("UsuariosIdUsuario");

                    b.ToTable("GrupoUsuario");
                });

            modelBuilder.Entity("NatSys.Entidades.Estilo", b =>
                {
                    b.Property<int>("IdEstilo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstilo"));

                    b.Property<decimal>("CoefFatigaFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CoefFatigaInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CoefFatigaMedio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEstilo");

                    b.ToTable("Estilos");
                });

            modelBuilder.Entity("NatSys.Entidades.Grupo", b =>
                {
                    b.Property<int>("IdGrupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGrupo"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdGrupo");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("NatSys.Entidades.Marca", b =>
                {
                    b.Property<int>("IdMarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMarca"));

                    b.Property<bool>("EsRecordPersonal")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAtleta")
                        .HasColumnType("int");

                    b.Property<int>("IdPrueba")
                        .HasColumnType("int");

                    b.Property<int?>("IdTorneo")
                        .HasColumnType("int");

                    b.Property<int>("LargoPileta")
                        .HasColumnType("int");

                    b.Property<string>("Tiempo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMarca");

                    b.HasIndex("IdAtleta");

                    b.HasIndex("IdPrueba");

                    b.HasIndex("IdTorneo");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("NatSys.Entidades.Pasaje", b =>
                {
                    b.Property<int>("IdPasaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPasaje"));

                    b.Property<int>("Distancia")
                        .HasColumnType("int");

                    b.Property<int>("IdPlanPasaje")
                        .HasColumnType("int");

                    b.Property<int>("NroTramo")
                        .HasColumnType("int");

                    b.Property<string>("Tiempo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPasaje");

                    b.HasIndex("IdPlanPasaje");

                    b.ToTable("Pasajes");
                });

            modelBuilder.Entity("NatSys.Entidades.Permiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPermiso"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPermiso");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("NatSys.Entidades.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersona"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPersona");

                    b.ToTable("Personas");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("NatSys.Entidades.PlanPasaje", b =>
                {
                    b.Property<int>("IdPlanPasaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlanPasaje"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAtleta")
                        .HasColumnType("int");

                    b.Property<int>("IdEntrenador")
                        .HasColumnType("int");

                    b.Property<int>("IdPrueba")
                        .HasColumnType("int");

                    b.Property<int>("LargoPileta")
                        .HasColumnType("int");

                    b.Property<string>("MarcaObjetivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPlanPasaje");

                    b.HasIndex("IdAtleta");

                    b.HasIndex("IdEntrenador");

                    b.HasIndex("IdPrueba");

                    b.ToTable("PlanesPasaje");
                });

            modelBuilder.Entity("NatSys.Entidades.Prueba", b =>
                {
                    b.Property<int>("IdPrueba")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrueba"));

                    b.Property<int>("Distancia")
                        .HasColumnType("int");

                    b.Property<int>("IdEstilo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPrueba");

                    b.HasIndex("IdEstilo");

                    b.ToTable("Pruebas");
                });

            modelBuilder.Entity("NatSys.Entidades.Sesion", b =>
                {
                    b.Property<int>("IdSesion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSesion"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Fin")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime2");

                    b.HasKey("IdSesion");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Sesiones");
                });

            modelBuilder.Entity("NatSys.Entidades.Torneo", b =>
                {
                    b.Property<int>("IdTorneo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTorneo"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("LargoPileta")
                        .HasColumnType("int");

                    b.Property<string>("NombreTorneo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sede")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTorneo");

                    b.ToTable("Torneos");
                });

            modelBuilder.Entity("NatSys.Entidades.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreguntaSeguridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RespuestaSeguridadHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdPersona");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("NatSys.Entidades.Atleta", b =>
                {
                    b.HasBaseType("NatSys.Entidades.Persona");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Atletas");
                });

            modelBuilder.Entity("NatSys.Entidades.Entrenador", b =>
                {
                    b.HasBaseType("NatSys.Entidades.Persona");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Entrenadores");
                });

            modelBuilder.Entity("AtletaPrueba", b =>
                {
                    b.HasOne("NatSys.Entidades.Atleta", null)
                        .WithMany()
                        .HasForeignKey("AtletaIdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatSys.Entidades.Prueba", null)
                        .WithMany()
                        .HasForeignKey("PruebasIdPrueba")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GrupoPermiso", b =>
                {
                    b.HasOne("NatSys.Entidades.Grupo", null)
                        .WithMany()
                        .HasForeignKey("GruposIdGrupo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatSys.Entidades.Permiso", null)
                        .WithMany()
                        .HasForeignKey("PermisosIdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GrupoUsuario", b =>
                {
                    b.HasOne("NatSys.Entidades.Grupo", null)
                        .WithMany()
                        .HasForeignKey("GruposIdGrupo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatSys.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NatSys.Entidades.Marca", b =>
                {
                    b.HasOne("NatSys.Entidades.Atleta", "Atleta")
                        .WithMany("Marcas")
                        .HasForeignKey("IdAtleta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NatSys.Entidades.Prueba", "Prueba")
                        .WithMany()
                        .HasForeignKey("IdPrueba")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NatSys.Entidades.Torneo", "TorneoRegistro")
                        .WithMany("Marcas")
                        .HasForeignKey("IdTorneo");

                    b.Navigation("Atleta");

                    b.Navigation("Prueba");

                    b.Navigation("TorneoRegistro");
                });

            modelBuilder.Entity("NatSys.Entidades.Pasaje", b =>
                {
                    b.HasOne("NatSys.Entidades.PlanPasaje", "Plan")
                        .WithMany("Pasajes")
                        .HasForeignKey("IdPlanPasaje")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("NatSys.Entidades.PlanPasaje", b =>
                {
                    b.HasOne("NatSys.Entidades.Atleta", "Atleta")
                        .WithMany()
                        .HasForeignKey("IdAtleta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NatSys.Entidades.Entrenador", "Entrenador")
                        .WithMany("Planes")
                        .HasForeignKey("IdEntrenador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NatSys.Entidades.Prueba", "Prueba")
                        .WithMany()
                        .HasForeignKey("IdPrueba")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atleta");

                    b.Navigation("Entrenador");

                    b.Navigation("Prueba");
                });

            modelBuilder.Entity("NatSys.Entidades.Prueba", b =>
                {
                    b.HasOne("NatSys.Entidades.Estilo", "Estilo")
                        .WithMany()
                        .HasForeignKey("IdEstilo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estilo");
                });

            modelBuilder.Entity("NatSys.Entidades.Sesion", b =>
                {
                    b.HasOne("NatSys.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NatSys.Entidades.Usuario", b =>
                {
                    b.HasOne("NatSys.Entidades.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("NatSys.Entidades.Atleta", b =>
                {
                    b.HasOne("NatSys.Entidades.Persona", null)
                        .WithOne()
                        .HasForeignKey("NatSys.Entidades.Atleta", "IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NatSys.Entidades.Entrenador", b =>
                {
                    b.HasOne("NatSys.Entidades.Persona", null)
                        .WithOne()
                        .HasForeignKey("NatSys.Entidades.Entrenador", "IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NatSys.Entidades.PlanPasaje", b =>
                {
                    b.Navigation("Pasajes");
                });

            modelBuilder.Entity("NatSys.Entidades.Torneo", b =>
                {
                    b.Navigation("Marcas");
                });

            modelBuilder.Entity("NatSys.Entidades.Atleta", b =>
                {
                    b.Navigation("Marcas");
                });

            modelBuilder.Entity("NatSys.Entidades.Entrenador", b =>
                {
                    b.Navigation("Planes");
                });
#pragma warning restore 612, 618
        }
    }
}
